# =================
# Node builder
# =================

FROM node:25.2-alpine3.21 as builder

WORKDIR /labstore-web

COPY web/package*.json ./
RUN npm install

COPY web .
RUN ls
RUN npm run build

# =================
# SvelteKit SPA
# =================

FROM nginx:1.29-alpine3.22

COPY infra/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /labstore-web/build /usr/share/nginx/html

EXPOSE 6790

CMD ["nginx", "-g", "daemon off;"]
