set shell := ["bash", "-uc"]

set dotenv-load
set dotenv-required
set dotenv-path := "../.env"

default:
    just -l

create:
    cd .. && docker compose -p labstore -f infra/compose.yml up --build -d

destroy:
    cd .. && docker compose -p labstore -f infra/compose.yml down
